import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import localFont from 'next/font/local'
import NavBar from "./_components/NavBar";
import { CgScrollV } from "react-icons/cg";
import Footer from "./_components/Footer";

const myFont = localFont({ src: '../../public/font/Almarai-Regular.ttf' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar">
      <body className={myFont.className} >
        <NavBar/>
        <main>
          {children}
          <a className="tw-fixed hover:tw-animate-spin  tw-transition tw-bottom-6 tw-right-6 tw-text-[50px] tw-bg-[#07284a] tw-text-white tw-p-2 tw-rounded-full" href="#top"><CgScrollV/></a>
        </main>
        <Footer/>
      </body>
    </html>
  );
}
